### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/Ordis#4]
- [x] Construct database table for items
- [x] Sync market API items with local database instead of dictionary
- [ ] Construct database table for orders
	- [ ] Users should be able to track order status via specific ID
	- [ ] Notifications when an item hits a certain price
